### ISSUE TITLE
Throw exception on a network card manually assigned ip address with unplugged state when enable local server

### ISSUE THREAD

**Issue by waiyanmintun** [MarcFletcher/NetworkComms.Net#35]
NetworkCommsDotNet.CommsSetupShutdownException
  HResult=0x80131500
  Message=It was not possible to open port #0 on 192.168.137.1. This endPoint may not support listening or possibly try again using a different port.
  Source=NetworkCommsDotNet
  StackTrace:
   at NetworkCommsDotNet.Connections.TCP.TCPConnectionListener.StartListening(EndPoint desiredLocalListenEndPoint, Boolean useRandomPortFailOver) in D:\Downloads\NetworkComms.Net-master\NetworkComms.Net-master\NetworkCommsDotNet\Connection\TCP\TCPConnectionListener.cs:line 146
   at NetworkCommsDotNet.Connections.Connection.StartListening[T](ConnectionListenerBase listener, T desiredLocalEndPoint, Boolean useRandomPortFailOver) in D:\Downloads\NetworkComms.Net-master\NetworkComms.Net-master\NetworkCommsDotNet\Connection\ConnectionListeners.cs:line 193
   at NetworkCommsDotNet.Connections.Connection.StartListening[T](ConnectionType connectionType, T desiredLocalEndPoint, Boolean allowDiscoverable) in D:\Downloads\NetworkComms.Net-master\NetworkComms.Net-master\NetworkCommsDotNet\Connection\ConnectionListeners.cs:line 110
   at Examples.ExamplesChat.WPF.ChatAppBase.RefreshNetworkCommsConfiguration() in D:\Downloads\NetworkComms.Net-master\NetworkComms.Net-master\ExamplesChat.WPF\ChatAppBase.cs:line 190
   at Examples.ExamplesChat.WPF.MainWindow.EnableLocalServer_CheckedUnChecked(Object sender, RoutedEventArgs e) in D:\Downloads\NetworkComms.Net-master\NetworkComms.Net-master\ExamplesChat.WPF\MainWindow.xaml.cs:line 155
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ToggleButton.OnToggle()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ExamplesWPFChat.App.Main()

**Comment by MarcFletcher** [comment]
Have you seen the bit that says:

> It was not possible to open port #0 on 192.168.137.1. This endPoint may not support listening or possibly try again using a different port.

I'd suggest you try listening on a specific numbered port that you know should be free.

**Comment by MarcFletcher** [comment]
Some error cases might not be handled in the included ExamplesChat.WPF app example. It's not intended to be bulletproof ;)
