### ISSUE TITLE
IExplicitSerializer doesn't work with custom classes

### ISSUE THREAD

**Issue by Mufanza** [MarcFletcher/NetworkComms.Net#42]
Hi,

Thanks for the hard work & the amazing library! Works great most of the time, though I believe I found a bug in the ExplicitSerialzier

**Version:** 3.0.4.1
**Situation:** Trying to send custom classes and deserialize them with ExplicitSerializer closes the connection abruptly. No error message is shown. The 'Deserialize' method of the IExplicitlySerialize interface doesn't seem to get called ('Serialize' seems to pass correctly). Sending primitive types/arrays works correctly.

**Example:**
The following example implements a custom _ExplicitModel_ class. For simplicity's sake, the Serialize and Deserialize methods were left empty (so we'd expect a default instance to pop on the server side, regardless of whatever data the client sends over)

```
public class ExplicitModel : IExplicitlySerialize
{
    int Id { get; set; }
    string Name { get; set; }

    public ExplicitModel() { }
    public void Serialize(Stream outputStream) { }
    public void Deserialize(Stream inputStream) { }
}

public ServerApp()
{
    var options = new SendReceiveOptions<ExplicitSerializer>();
    NetworkComms.AppendGlobalIncomingPacketHandler<ExplicitModel>("ExplicitModel", ReceiveExplicitModel, options);
    var connectionsTCP = Connection.StartListening
    (
        ConnectionType.TCP,
        new System.Net.IPEndPoint(System.Net.IPAddress.Any, 8754)
    );
    Console.ReadKey();
}

private static void ReceiveExplicitModel(PacketHeader header, Connection connection, ExplicitModel model) =>
    Console.WriteLine($"Received model explicitly");

public ClientApp()
{
    var options = new SendReceiveOptions<ExplicitSerializer>();
    var connection = TCPConnection.GetConnection(new ConnectionInfo("127.0.0.1", 8754));
    var model = new ExplicitModel() { Id = 5, Name = "Foo" }
    connection.SendObject<ExplicitModel>("ExplicitModel", model, options);
    Console.ReadKey();
}
```

**Comment by MarcFletcher** [comment]
Thanks for the compliments and great that you're using the library well.

Out of interest this seems potentially similar to https://stackoverflow.com/questions/42751099/networkcomms-custom-object-error-objecttoserialize-must-implement-iexplicitly? 

If it's different are there any other logs or error messages available ?

Kind regards.

**Comment by Mufanza** [comment]
Thanks for the quick reply!
It's different - the StackOverflow issue that you linked was regarding to ProtobufSerializer, but the issue that I've encountered is related to ExplicitSerializer

The app indeed does generates a logfile:
```
Base Exception Type: System.ArgumentException: Provided type NetworkLearning_Unified.ExplicitModel either does not have a parameterless constructor or does not implement IExplicitlySerialize
Parameter name: resultType
   at NetworkCommsDotNet.DPSBase.ExplicitSerializer.DeserialiseDataObjectInt(Stream inputStream, Type resultType, Dictionary`2 options)
   at NetworkCommsDotNet.DPSBase.DataSerializer.DeserialiseGeneralObject[T](MemoryStream receivedObjectStream, List`1 dataProcessors, Dictionary`2 options)
   at NetworkCommsDotNet.DPSBase.DataSerializer.DeserialiseDataObject[T](MemoryStream receivedObjectStream, List`1 dataProcessors, Dictionary`2 options)
   at NetworkCommsDotNet.Tools.PacketTypeHandlerDelegateWrapper`1.DeSerialize(MemoryStream incomingBytes, SendReceiveOptions options)
   at NetworkCommsDotNet.NetworkComms.TriggerAllPacketHandlers(PacketHeader packetHeader, Connection connection, MemoryStream dataStream, SendReceiveOptions options, Boolean ignoreUnknownPacketTypeOverride)
   at NetworkCommsDotNet.NetworkComms.TriggerAllPacketHandlers(PacketHeader packetHeader, Connection connection, MemoryStream dataStream, SendReceiveOptions options)
   at NetworkCommsDotNet.NetworkComms.CompleteIncomingItemTask(Object priorityQueueItemObj)

Stack Trace:    at NetworkCommsDotNet.DPSBase.ExplicitSerializer.DeserialiseDataObjectInt(Stream inputStream, Type resultType, Dictionary`2 options)
   at NetworkCommsDotNet.DPSBase.DataSerializer.DeserialiseGeneralObject[T](MemoryStream receivedObjectStream, List`1 dataProcessors, Dictionary`2 options)
   at NetworkCommsDotNet.DPSBase.DataSerializer.DeserialiseDataObject[T](MemoryStream receivedObjectStream, List`1 dataProcessors, Dictionary`2 options)
   at NetworkCommsDotNet.Tools.PacketTypeHandlerDelegateWrapper`1.DeSerialize(MemoryStream incomingBytes, SendReceiveOptions options)
   at NetworkCommsDotNet.NetworkComms.TriggerAllPacketHandlers(PacketHeader packetHeader, Connection connection, MemoryStream dataStream, SendReceiveOptions options, Boolean ignoreUnknownPacketTypeOverride)
   at NetworkCommsDotNet.NetworkComms.TriggerAllPacketHandlers(PacketHeader packetHeader, Connection connection, MemoryStream dataStream, SendReceiveOptions options)
   at NetworkCommsDotNet.NetworkComms.CompleteIncomingItemTask(Object priorityQueueItemObj)

```

BaseException claims that the custom class "_either does not have a parameterless constructor or does not implement IExplicitlySerialize_", but neither is true (as you can see from the example code above)

**Comment by Mufanza** [comment]
That's ok!
Hmm I don't trust myself in fixing the actual issue (perhaps there really is a good reason for enforcing the 'private' accessibility and changing that would break something). But elaborating on the error message is the least I can do :)

If anybody needs the constructor to be public, they can always implement their own DataSerializer where this isn't a requirement. I tested such approach and it seems to work without any issues.

**Comment by MarcFletcher** [comment]
Hahaha, fortune favours the bold! 

Many thanks for the PR!

Thanks again for your support of our library!
